import {
  LayoutDashboard,
  PlugZap,
  Users,
  GitFork,
  Filter,
  Send,
  Settings,
  ChevronLeft,
  ChevronRight,
  Sun,
  Moon,
  Activity,
  CheckCircle2,
  XCircle,
  Clock,
  Server,
  MessageSquare,
  BarChart,
  MoreVertical,
  ArrowUp,
  ArrowDown,
  Signal,
  Waves,
  Power,
  PowerOff,
  Menu,
  X,
  Building,
} from 'lucide-react';
export const Icons = {
  dashboard: LayoutDashboard,
  connectors: PlugZap,
  users: Users,
  routing: GitFork,
  filters: Filter,
  sendMessage: Send,
  settings: Settings,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  sun: Sun,
  moon: Moon,
  activity: Activity,
  success: CheckCircle2,
  error: XCircle,
  pending: Clock,
  server: Server,
  messages: MessageSquare,
  barChart: BarChart,
  moreVertical: MoreVertical,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  signal: Signal,
  logo: Waves,
  power: Power,
  powerOff: PowerOff,
  menu: Menu,
  close: X,
  company: Building,
};