import { Connector, ConnectorStatus, JasminUser, Group, Route, RouteType, MessageFilter, FilterType } from './types';
export const MOCK_CONNECTORS: Connector[] = [
  {
    id: 'conn-01',
    cid: 'smpp-us-01',
    type: 'smppc',
    status: ConnectorStatus.UP,
    host: 'smpp.us.provider.com',
    port: 2775,
    username: 'user01',
    starts: 102,
    stops: 1,
    submit_sm_throughput: 50,
  },
  {
    id: 'conn-02',
    cid: 'smpp-eu-01',
    type: 'smppc',
    status: ConnectorStatus.DOWN,
    host: 'smpp.eu.provider.com',
    port: 2775,
    username: 'user02',
    starts: 5,
    stops: 5,
    submit_sm_throughput: 0,
  },
  {
    id: 'conn-03',
    cid: 'http-api-01',
    type: 'httpc',
    status: ConnectorStatus.UP,
    host: 'api.provider.com',
    port: 443,
    username: 'api-key-user',
    starts: 250,
    stops: 2,
    submit_sm_throughput: 150,
  },
  {
    id: 'conn-04',
    cid: 'smpp-backup-01',
    type: 'smppc',
    status: ConnectorStatus.RECONNECTING,
    host: 'smpp.backup.provider.com',
    port: 2776,
    username: 'user01_bak',
    starts: 15,
    stops: 14,
    submit_sm_throughput: 5,
  },
];
export const MOCK_JASMIN_USERS: JasminUser[] = [
  {
    id: 'user-01',
    uid: 'user-01',
    username: 'customer_a',
    gid: 'group-01',
    balance: 100.5,
    throughput: 10,
    enabled: true,
  },
  {
    id: 'user-02',
    uid: 'user-02',
    username: 'customer_b',
    gid: 'group-01',
    balance: 50.0,
    throughput: 5,
    enabled: true,
  },
  {
    id: 'user-03',
    uid: 'user-03',
    username: 'customer_c_disabled',
    gid: 'group-02',
    balance: 0,
    throughput: 10,
    enabled: false,
  },
];
export const MOCK_GROUPS: Group[] = [
  {
    id: 'group-01',
    gid: 'group-01',
    enabled: true,
  },
  {
    id: 'group-02',
    gid: 'group-02',
    enabled: false,
  },
  {
    id: 'default',
    gid: 'default',
    enabled: true,
  },
];
export const MOCK_ROUTES: Route[] = [
  {
    id: 'route-01',
    type: RouteType.STATIC,
    order: 10,
    connectorId: 'conn-01',
    filters: ['filter_us_only'],
  },
  {
    id: 'route-02',
    type: RouteType.FAILOVER,
    order: 20,
    connectorId: 'conn-02',
    filters: ['filter_eu_only'],
  },
  {
    id: 'route-03',
    type: RouteType.STANDARD,
    order: 100,
    connectorId: 'conn-03',
    filters: [],
  },
  {
    id: 'route-04',
    type: RouteType.RANDOM,
    order: 50,
    connectorId: 'conn-04',
    filters: [],
  },
];
export const MOCK_FILTERS: MessageFilter[] = [
  {
    id: 'filter-01',
    fid: 'block_spam',
    type: FilterType.SHORT_MESSAGE_FILTER,
    description: 'Blocks messages containing "spam"',
    routes: ['10', '20'],
  },
  {
    id: 'filter-02',
    fid: 'allow_customer_a',
    type: FilterType.USER_FILTER,
    description: 'Only allows messages from user customer_a',
    routes: ['10'],
  },
  {
    id: 'filter-03',
    fid: 'us_source',
    type: FilterType.SOURCE_ADDR_FILTER,
    description: 'Matches US source addresses',
    routes: ['100'],
  },
];